
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // No `engine` key: Prisma 7 dropped the classic query engine in favour of
  // driver adapters, and the option no longer exists on the config type. The
  // runtime connection now comes from PrismaPg in src/lib/prisma.ts; this
  // `datasource` is still needed, but only for the CLI's migrate/introspect.
  datasource: {
    url: env("DATABASE_URL"),
  },
});
